### ISSUE TITLE
Misc improvements 

### ISSUE THREAD

**Issue by Mikanebu** [datasets/exchange-rates#1]
We want to update readme and add graphs, so it will look better and attractive. 

## Acceptance criteria

* [x] readme is updated with more details
* [x] graph is added

## Tasks

* [x] Update readme and add views property into `datapackage.json`

## Analysis

Great work on curating exchange rates dataset https://github.com/datasets/exchange-rates.
It would be nice to have csv files in such order
```
Date, Country, Value
1971-01-01, Australia, 0.8944
1972-02-01, Australia, 0.8898
```
What do you think?

Also, for metadata, it would be nice to have` title, name, licences, sources, contributors` etc. You can take a look on specifications https://frictionlessdata.io/specs/data-package/.`
`README.md` needs improvements
Bonus point to have `views`
 property, please see http://datahub.io/docs/features/views

**Comment by Mikanebu** [comment]
FIXED, added views and updated readme with more details
